'use strict'

module.exports = {
  APP_STATE_GET: 'APP_STATE_GET',
  APP_INITIAL_STATE: 'APP_INITIAL_STATE',
  APP_GET_INITIAL_STATE: 'APP_GET_INITIAL_STATE',
  APP_SET_STATE: 'APP_SET_STATE',
  APP_START: 'APP_START',
  APP_STATE: 'APP_STATE',
  APP_CHANGED: 'APP_CHANGED',
  APP_CLEAR_VIEW: 'APP_CLEAR_VIEW',
  APP_EDITOR_FOCUS: 'APP_EDITOR_FOCUS'
}
