'use strict'

module.exports = {
  GIST_GET: 'GIST_GET',
  GIST_CREATE: 'GIST_CREATE',
  GIST_DELETE: 'GIST_DELETE',
  GIST_UPDATE: 'GIST_UPDATE',
  GISTS_ALL: 'GISTS_ALL',
  GIST_RETURNED: 'GIST_RETURNED',
  GIST_ALL_RETURNED: 'GIST_ALL_RETURNED',
  GIST_UPDATED: 'GIST_UPDATED',
  GIST_ERROR: 'GIST_ERROR'
}
