'use strict'

module.exports = {
  USER_LOGIN: 'USER_LOGIN',
  AUTH_START: 'AUTH_START',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGGEDOUT: 'USER_LOGGEDOUT'
}
